### ISSUE TITLE
Issue while installation 

### ISSUE THREAD

**Issue by jamsheer-thottathil** [Workpop/graphql-metrics#4]
I am getting following error while installing 

error An unexpected error occurred: "https://registry.yarnpkg.com/@workpop%2fgraphql-metrics: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/root/jamsheer/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by abhiaiyer91** [comment]
@jamsheer-thottathil thanks for the issue, should be good now
